 steps:    
# Perform Maven build for the java project 
 - name: maven:3-jdk-8
   entrypoint: mvn
   args: ['clean', 'package']   
# Perform code quality analysis using SonarQube       
 - name: 'gcr.io/$PROJECT_ID/sonar-scanner:latest'
   args: 
     - '-Dsonar.host.url=https://sonarcloud.io'
     - '-Dsonar.login=e31545402887b45010a5fd84bcfb8435916c207c'
     - '-Dsonar.projectKey=googledevopsdemo'
     - '-Dsonar.organization=csidemo'
     - '-Dsonar.sources=./src'  
     - '-Dsonar.java.binaries=./target/classes'
# Build Docker image using tomcat and war file     
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/c-si-devsecops/googledevopsdemo', '.']
# Push Docker image to Google Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/c-si-devsecops/googledevopsdemo']
# deploy container image to GKE
 - name: "gcr.io/cloud-builders/gke-deploy"
   args:
   - run
   - --filename=kubedeployment.yaml
   - --image=gcr.io/c-si-devsecops/googledevopsdemo:latest
   - --location=asia-south1-a
   - --cluster=devsecopspocgks   
# Perform Penetration Testing for Demo Health Care Portal    
 - name: gcr.io/cloud-builders/docker
   entrypoint: 'bash'
   args:
     - -c
     - |
       docker run -t owasp/zap2docker-weekly zap-api-scan.py -t https://demoapp-dot-c-si-devsecops.el.r.appspot.com/ -f openapi -I   
# Upload artifcats to Google Cloud Storage   
 artifacts:
   objects:
     location: 'gs://devsecops-bucket/demoapp'
     paths: ['./target/*.war']
