 steps:
# Perform Maven build for the java project     
 - name: maven:3-jdk-8
   entrypoint: mvn
   args: ['clean', 'package']   
# Perform code quality analysis using SonarQube    
 - name: 'gcr.io/$PROJECT_ID/sonar-scanner:latest'
   args: 
     - '-Dsonar.host.url=https://sonarcloud.io'
     - '-Dsonar.login=e31545402887b45010a5fd84bcfb8435916c207c'
     - '-Dsonar.projectKey=googledevopsdemo'
     - '-Dsonar.organization=csidemo'
     - '-Dsonar.sources=./src'  
     - '-Dsonar.java.binaries=./target/classes'
# Perform Database deployment in Azure Cloud
 - name: 'gcr.io/cloud-builders/gcloud'
   entrypoint: 'bash'
   args:
   - '-c'
   - |
     chmod u+x ./dbFile/db_sh.sh
     apt update
     apt install -y mysql-client
     ./dbFile/db_sh.sh 
# Perform App Engine deployment in Google Cloud for Demo Health Care Portal     
 - name: maven:3-jdk-8
   entrypoint: mvn
   args: ['appengine:deploy']
# Perform Penetration Testing for Demo Health Care Portal    
 - name: gcr.io/cloud-builders/docker
   entrypoint: 'bash'
   args:
     - -c
     - |
       docker run -t owasp/zap2docker-weekly zap-api-scan.py -t https://demoapp-dot-c-si-devsecops.el.r.appspot.com/ -f openapi -I
# Upload artifcats to Google Cloud Storage     
 artifacts:
   objects:
     location: 'gs://devsecops-bucket/demoapp'
     paths: ['./target/*.war']
