  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcaredemo0
  labels:
    app: healthcaredemo0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthcaredemo0
  template:
    metadata:
      labels:
        app: healthcaredemo0
    spec:
      containers:
      - name: healthcaredemo0
        image: redis
        ports:
        - containerPort: 6379
          name: redis
     
---

apiVersion: v1
kind: Service
metadata:
  name: healthcaredemo0
spec:
  type: ClusterIP
  ports:
  - port: 6379
  selector:
    app: healthcaredemo0

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcaredemo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  selector:
    matchLabels:
      app: healthcaredemo
  template:
    metadata:
      labels:
        app: healthcaredemo
    spec:
      containers:
      - name: healthcaredemo
        image: gcr.io/c-si-devsecops/googledevopsdemo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: REDIS
          value: "healthcaredemo0"

---

apiVersion: v1
kind: Service
metadata:    
  name: healthcaredemo
spec:  
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: healthcaredemo
