/*
 * This file was automatically generated by EvoSuite
 * Tue Jun 22 10:05:40 GMT 2021
 */

package com.neu.Rohit.pojo;

import org.junit.Test;
import static org.junit.Assert.*;
import com.neu.Rohit.pojo.BookingDetails;
import com.neu.Rohit.pojo.Car;
import java.util.Set;
import org.junit.runner.RunWith;

public class Car_ESTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Car car0 = new Car();
      car0.setTypicalSeating("");
      String string0 = car0.getTypicalSeating();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Car car0 = new Car();
      car0.setTotalPrice("hv\"");
      String string0 = car0.getTotalPrice();
      assertEquals("hv\"", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Car car0 = new Car();
      car0.setTotalPrice("");
      String string0 = car0.getTotalPrice();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Car car0 = new Car();
      car0.setTaxesAndFees("tUFfp");
      String string0 = car0.getTaxesAndFees();
      assertEquals("tUFfp", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Car car0 = new Car("", (String) null);
      car0.setTaxesAndFees("");
      String string0 = car0.getTaxesAndFees();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Car car0 = new Car("06~KBIw<", "P");
      car0.setRentalDays("{Ii5Y9Ss^");
      car0.getRentalDays();
      assertEquals("06~KBIw<", car0.getName());
      assertEquals("P", car0.getModel());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Car car0 = new Car("DgaP'&)Y8-8K*cM-<k", "DgaP'&)Y8-8K*cM-<k");
      car0.setRentalDays("");
      String string0 = car0.getRentalDays();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Car car0 = new Car();
      car0.setRegistrationNo(2116L);
      long long0 = car0.getRegistrationNo();
      assertEquals(2116L, long0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Car car0 = new Car();
      car0.setRegistrationNo((-3232L));
      long long0 = car0.getRegistrationNo();
      assertEquals((-3232L), long0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Car car0 = new Car("}h^M>@KmMfzq Vb", "}h^M>@KmMfzq Vb");
      String string0 = car0.getName();
      assertEquals("}h^M>@KmMfzq Vb", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Car car0 = new Car();
      car0.setName("");
      String string0 = car0.getName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Car car0 = new Car();
      String string0 = car0.getModel();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Car car0 = new Car();
      car0.setModel("");
      String string0 = car0.getModel();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Car car0 = new Car("com.neu.Rohit.pojo.User", "_>AA1Nsrq`2CaM(");
      car0.setHWRefNumber("");
      car0.getHWRefNumber();
      assertEquals("_>AA1Nsrq`2CaM(", car0.getModel());
      assertEquals("com.neu.Rohit.pojo.User", car0.getName());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Car car0 = new Car("DgaP'&)Y8-8K*cM-<k", "DgaP'&)Y8-8K*cM-<k");
      car0.setDailyRate("DgaP'&)Y8-8K*cM-<k");
      String string0 = car0.getDailyRate();
      assertEquals("DgaP'&)Y8-8K*cM-<k", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Car car0 = new Car();
      car0.setDailyRate("");
      String string0 = car0.getDailyRate();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Car car0 = new Car();
      car0.setBookingDetails((Set<BookingDetails>) null);
      Set<BookingDetails> set0 = car0.getBookingDetails();
      assertNull(set0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Car car0 = new Car();
      long long0 = car0.getRegistrationNo();
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Car car0 = new Car("(4UW !Y+rrFCHo", "(4UW !Y+rrFCHo");
      car0.setHWRefNumber("(4UW !Y+rrFCHo");
      String string0 = car0.getHWRefNumber();
      assertEquals("(4UW !Y+rrFCHo", string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Car car0 = new Car("(4UW !Y+rrFCHo", "(4UW !Y+rrFCHo");
      String string0 = car0.getDailyRate();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Car car0 = new Car("(4UW !Y+rrFCHo", "(4UW !Y+rrFCHo");
      car0.setTypicalSeating("(4UW !Y+rrFCHo");
      String string0 = car0.getTypicalSeating();
      assertEquals("(4UW !Y+rrFCHo", string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Car car0 = new Car();
      String string0 = car0.getTaxesAndFees();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Car car0 = new Car("(4UW !Y+rrFCHo", "(4UW !Y+rrFCHo");
      String string0 = car0.getModel();
      assertEquals("(4UW !Y+rrFCHo", string0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Car car0 = new Car();
      String string0 = car0.getTotalPrice();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Car car0 = new Car("(4UW !Y+rrFCHo", "(4UW !Y+rrFCHo");
      String string0 = car0.getHWRefNumber();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Car car0 = new Car("(4UW !Y+rrFCHo", "(4UW !Y+rrFCHo");
      String string0 = car0.getTypicalSeating();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Car car0 = new Car();
      String string0 = car0.getRentalDays();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Car car0 = new Car();
      String string0 = car0.getName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Car car0 = new Car();
      Set<BookingDetails> set0 = car0.getBookingDetails();
      car0.setBookingDetails(set0);
      assertNull(car0.getName());
  }
}
