/*
 * This file was automatically generated by EvoSuite
 * Tue Jun 22 10:06:22 GMT 2021
 */

package com.neu.Rohit.pojo;

import org.junit.Test;
import static org.junit.Assert.*;
import com.neu.Rohit.pojo.Payment;
import com.neu.Rohit.pojo.User;
import org.junit.runner.RunWith;

public class Payment_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      User user0 = new User("hi<7xHMh'e0apo7", "com.neu.Rohit.pojo.User", "com.neu.Rohit.pojo.User");
      Payment payment0 = new Payment((String) null, "", (String) null, user0);
      user0.setUserID((-1783L));
      User user1 = payment0.getUser();
      assertSame(user0, user1);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      User user0 = new User((String) null, "Cn)]8!&I%]", "VkoCYQmx{fNUs^`");
      Payment payment0 = new Payment("xRPyM]g5Ch8SD`+Z", "Cn)]8!&I%]", "", user0);
      payment0.setPaymentID(2417L);
      long long0 = payment0.getPaymentID();
      assertEquals(2417L, long0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      User user0 = new User(".u$\":Z]NVSF=E");
      Payment payment0 = new Payment(".u$\":Z]NVSF=E", "", "", user0);
      String string0 = payment0.getCardNo();
      assertEquals(".u$\":Z]NVSF=E", string0);
      assertEquals("", payment0.getExpiryDate());
      assertEquals("", payment0.getCvv());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      User user0 = new User("", "20=dH`EZQo", "20=dH`EZQo");
      Payment payment0 = new Payment("", "", "20=dH`EZQo", user0);
      String string0 = payment0.getCardNo();
      assertEquals("", payment0.getExpiryDate());
      assertEquals("", string0);
      assertEquals("20=dH`EZQo", payment0.getCvv());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      User user0 = new User("9_a`iNA.s~d[xW");
      Payment payment0 = new Payment("9_a`iNA.s~d[xW", "", "9_a`iNA.s~d[xW", user0);
      payment0.setCardHolderName("");
      payment0.getCardHolderName();
      assertEquals("", payment0.getExpiryDate());
      assertEquals("9_a`iNA.s~d[xW", payment0.getCardNo());
      assertEquals("9_a`iNA.s~d[xW", payment0.getCvv());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      User user0 = new User("mi9]X");
      Payment payment0 = new Payment("mi9]X", "mi9]X", "mi9]X", user0);
      User user1 = payment0.getUser();
      assertNull(user1.getPassword());
  }
}
